name: etlpipeline
on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: job1
        run: echo "extract.py executed"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: job2
        run: echo "transform.py executed"
  job3:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: job3
        run: echo "load.py executed"
  job4:
    needs: job2
    runs-on: ubuntu-latest
    steps:
      - name: job4
        run: echo "extract.py executed "
  job5:
    needs: job3
    runs-on: ubuntu-latest
    steps:
      - name: job5
        run: echo "transform.py executed "
  job6:
    needs: [job4, job5]
    runs-on: ubuntu-latest
    steps:
      - name: job6
        run: echo "load.py executed "
