name: etlpipeline
on:
  push:
    branches:
      - main

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: extract
        run: echo "extract.py executed"
  transform:
    needs: extract
    runs-on: ubuntu-latest
    steps:
      - name: transform
        run: echo "transform.py executed"
  load:
    needs: extract
    runs-on: ubuntu-latest
    steps:
      - name: load
        run: echo "load.py executed"
  extract:
    needs: transform
    runs-on: ubuntu-latest
    steps:
      - name: extract
        run: echo "extract.py executed "
  transform:
    needs: load
    runs-on: ubuntu-latest
    steps:
      - name: transform
        run: echo "transform.py executed "
  load:
    needs: [extract, transform]
    runs-on: ubuntu-latest
    steps:
      - name: load
        run: echo "load.py executed "
